import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import HeroSection from '../components/home/HeroSection'
import BestStories from '../components/home/BestStories'
import EditorsChoice from '../components/home/EditorsChoice'
import AllPost from '../components/home/AllPost'
import Subscribe from '../components/home/Subscribe'
import Loader from '../components/shared-components/Loader'
import { useEffect, useState } from 'react'
import useTitleHook from '../components/customHook/useTitleHook'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useTitleHook('Home')

  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false)
    }, 1500);
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Treatise</title>
      </Head>
      
      {
        isLoading ? <Loader></Loader> :
        <div className="mt-20 sm:mt-[120px] md:[120px] lg:mt-[140px] xl:mt-[160px]">
        
        <HeroSection></HeroSection>

        <BestStories></BestStories>

        <EditorsChoice></EditorsChoice>

        <AllPost></AllPost>

        <Subscribe></Subscribe>

      `</div>
      }

    </>
  )
}
